pi = 3.14159

BASE_OBJECT = "BASE"
PATH_OBJECT = "PATH"
EMPTY_OBJECT = "EMPTY"
PLATE_OBJECT = "PLATE"
FOV_OBJECT = "FOV"
IMPORT_PLATE_OBJECT = "IMPORTPLATE"
MAIN_TEXT_OBJECT = "MAINTEXT"
UPPER_TEXT_OBJECT = "UPPERTEXT"
LEFT_NURNIE_OBJECT = "NURNIE_LEFT"
RIGHT_NURNIE_OBJECT = "NURNIE_RIGHT"
LEFT_NUR_OBJECT = "NUR_LEFT"
RIGHT_NUR_OBJECT = "NUR_RIGHT"
MAIN_TEXT_BOOL_OBJECT = "MAINTEXTBOOL"
UPPER_TEXT_BOOL_OBJECT = "UPPERTEXTBOOL"
LEFT_NUR_EXPORT_OBJECT = "NUR_LEFT.002"
RIGHT_NUR_EXPORT_OBJECT = "NUR_RIGHT.002"
LEFT_NURNIE_DUPLICATE_OBJECT = "NURNIE_LEFT.001"
RIGHT_NURNIE_DUPLICATE_OBJECT = "NURNIE_RIGHT.001"
LEFT_NUR_DUPLICATE_OBJECT = "NUR_LEFT.001"
RIGHT_NUR_DUPLICATE_OBJECT = "NUR_RIGHT.001"
REALIZED_RIGHT_NURNIE_OBJECT = "RIGHT_NURNIE"
PLATE_FOV_BOOLEAN_MODIFIER = "Boolean"
PLATE_MAIN_TEXT_BOOLEAN_MODIFIER = "BooleanTextMain"
PLATE_UPPER_TEXT_BOOLEAN_MODIFIER = "BooleanTextUpper"

NAMEPLATE_LEGACY_OBJECTS = (
    BASE_OBJECT,
    PATH_OBJECT,
    EMPTY_OBJECT,
    PLATE_OBJECT,
    FOV_OBJECT,
    MAIN_TEXT_OBJECT,
    UPPER_TEXT_OBJECT,
    LEFT_NURNIE_OBJECT,
    RIGHT_NURNIE_OBJECT,
    LEFT_NUR_OBJECT,
    RIGHT_NUR_OBJECT,
    IMPORT_PLATE_OBJECT,
    "FOV1",
    "FOV2",
    REALIZED_RIGHT_NURNIE_OBJECT,
)
