pi = 3.14159

BASE_OBJECT = "BASE"
PATH_OBJECT = "PATH"
EMPTY_OBJECT = "EMPTY"
PLATE_OBJECT = "PLATE"
FOV_OBJECT = "FOV"
IMPORT_PLATE_OBJECT = "IMPORTPLATE"
MAIN_TEXT_OBJECT = "MAINTEXT"
UPPER_TEXT_OBJECT = "UPPERTEXT"
LEFT_NURNIE_OBJECT = "NURNIE_LEFT"
RIGHT_NURNIE_OBJECT = "NURNIE_RIGHT"
LEFT_NUR_OBJECT = "NUR_LEFT"
RIGHT_NUR_OBJECT = "NUR_RIGHT"

NAMEPLATE_LEGACY_OBJECTS = (
    BASE_OBJECT,
    PATH_OBJECT,
    EMPTY_OBJECT,
    PLATE_OBJECT,
    FOV_OBJECT,
    MAIN_TEXT_OBJECT,
    UPPER_TEXT_OBJECT,
    LEFT_NURNIE_OBJECT,
    RIGHT_NURNIE_OBJECT,
    LEFT_NUR_OBJECT,
    RIGHT_NUR_OBJECT,
    IMPORT_PLATE_OBJECT,
    "FOV1",
    "FOV2",
    "RIGHT_NURNIE",
)
